import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DEV_SERVER_ID,
  VERIFICATION_CHANNEL,
  VERIFICATION_OUTPUT_CHANNEL,
  BLACKLIST_ROLE,
  SERVER_NAME,
  RULES_CHANNEL,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !DEV_SERVER_ID ||
  !VERIFICATION_CHANNEL ||
  !VERIFICATION_OUTPUT_CHANNEL ||
  !BLACKLIST_ROLE ||
  !SERVER_NAME ||
  !RULES_CHANNEL
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DEV_SERVER_ID,
  VERIFICATION_CHANNEL,
  VERIFICATION_OUTPUT_CHANNEL,
  BLACKLIST_ROLE,
  SERVER_NAME,
  RULES_CHANNEL,
};
